"""Constants for Frame Art Mode Sync integration."""

from __future__ import annotations

DOMAIN = "frame_artmode_sync"

# Default values
DEFAULT_ENABLED = True
DEFAULT_ACTIVE_START = "06:00:00"
DEFAULT_ACTIVE_END = "22:00:00"
DEFAULT_RETURN_DELAY_SECONDS = 3
DEFAULT_COOLDOWN_SECONDS = 20
DEFAULT_ATV_DEBOUNCE_SECONDS = 2
DEFAULT_ATV_GRACE_SECONDS_ON_DISCONNECT = 60
DEFAULT_OVERRIDE_MINUTES = 30
DEFAULT_RESYNC_INTERVAL_MINUTES = 15
DEFAULT_MAX_DRIFT_CORRECTIONS_PER_HOUR = 6
DEFAULT_DRIFT_CORRECTION_COOLDOWN_MINUTES = 10
DEFAULT_MOTION_DETECTION_GRACE_MINUTES = 15
DEFAULT_MAX_COMMANDS_PER_5MIN = 25
DEFAULT_BREAKER_COOLDOWN_MINUTES = 10
DEFAULT_STARTUP_GRACE_SECONDS = 60
DEFAULT_WAKE_RETRY_DELAY_SECONDS = 3
DEFAULT_REMOTE_WAKE_RETRIES = 2
DEFAULT_REMOTE_WAKE_DELAY_SECONDS = 2
DEFAULT_WOL_RETRIES = 1
DEFAULT_WOL_DELAY_SECONDS = 2
DEFAULT_WOL_BROADCAST = "255.255.255.255"
DEFAULT_WAKE_STARTUP_GRACE_SECONDS = 60
DEFAULT_DRY_RUN = False
DEFAULT_FRAME_PORT = 8002
DEFAULT_BASE_PAIRING_NAME = "FrameArtSync"

# Modes
MODE_OFF = "OFF"
MODE_ART = "ART"
MODE_ATV = "ATV"

# Phase states
PHASE_IDLE = "idle"
PHASE_SWITCHING_TO_ATV = "switching_to_atv"
PHASE_RETURNING_TO_ART = "returning_to_art"
PHASE_ENFORCING_NIGHT = "enforcing_night"
PHASE_AWAY_OFF = "away_off"
PHASE_BREAKER_OPEN = "breaker_open"
PHASE_DEGRADED = "degraded"
PHASE_MANUAL_OVERRIDE = "manual_override"
PHASE_DRY_RUN = "dry_run"

# Health states
HEALTH_OK = "ok"
HEALTH_DEGRADED = "degraded"
HEALTH_BREAKER_OPEN = "breaker_open"

# Night behaviors
NIGHT_BEHAVIOR_DO_NOTHING = "do_nothing"
NIGHT_BEHAVIOR_FORCE_OFF = "force_off"
NIGHT_BEHAVIOR_FORCE_ART = "force_art"

# Presence modes
PRESENCE_MODE_DISABLED = "disabled"
PRESENCE_MODE_ENTITY = "entity"

# Away policies
AWAY_POLICY_DISABLED = "disabled"
AWAY_POLICY_TURN_TV_OFF = "turn_tv_off"
AWAY_POLICY_KEEP_ART_ON = "keep_art_on"

# Input modes
INPUT_MODE_NONE = "none"
INPUT_MODE_HDMI1 = "hdmi1"
INPUT_MODE_HDMI2 = "hdmi2"
INPUT_MODE_HDMI3 = "hdmi3"
INPUT_MODE_LAST_USED = "last_used"

# ATV active modes
ATV_ACTIVE_MODE_PLAYING_ONLY = "playing_only"
ATV_ACTIVE_MODE_PLAYING_OR_PAUSED = "playing_or_paused"
ATV_ACTIVE_MODE_POWER_ON = "power_on"

# Default ATV active mode
DEFAULT_ATV_ACTIVE_MODE_PLAYING_OR_PAUSED = ATV_ACTIVE_MODE_PLAYING_OR_PAUSED

# Unknown behaviors
UNKNOWN_BEHAVIOR_IGNORE = "ignore"
UNKNOWN_BEHAVIOR_TREAT_AS_HOME = "treat_as_home"
UNKNOWN_BEHAVIOR_TREAT_AS_AWAY = "treat_as_away"

# Timeouts and limits
VERIFY_TIMEOUT_TOTAL = 8.0  # seconds
POWER_TOGGLE_TIMEOUT = 10.0
CONNECTION_TIMEOUT = 30.0  # Increased from 10.0 to allow TV more time to wake/respond
COMMAND_TIMEOUT = 5.0
MAX_WAKE_ATTEMPTS = 2
MAX_RECENT_EVENTS = 20

# Backoff (seconds)
BACKOFF_INITIAL = 10
BACKOFF_MAX = 60
BACKOFF_MULTIPLIER = 3

# Event types
EVENT_TYPE_ATV_ON = "atv_on"
EVENT_TYPE_ATV_OFF = "atv_off"
EVENT_TYPE_PRESENCE_CHANGE = "presence_change"
EVENT_TYPE_TIME_WINDOW_CHANGE = "time_window_change"
EVENT_TYPE_RESYNC = "resync"
EVENT_TYPE_MANUAL = "manual"
EVENT_TYPE_STARTUP = "startup"
EVENT_TYPE_DRIFT_DETECTED = "drift_detected"
EVENT_TYPE_OVERRIDE_ACTIVATED = "override_activated"
EVENT_TYPE_OVERRIDE_CLEARED = "override_cleared"
EVENT_TYPE_BREAKER_OPENED = "breaker_opened"
EVENT_TYPE_BREAKER_CLOSED = "breaker_closed"
EVENT_TYPE_DEGRADED = "degraded"
EVENT_TYPE_RECOVERED = "recovered"

# Action types
ACTION_SET_ART_ON = "set_art_on"
ACTION_SET_ART_OFF = "set_art_off"
ACTION_INPUT_SWITCH = "input_switch"
ACTION_TV_OFF = "tv_off"
ACTION_WOL = "wol"
ACTION_REMOTE_WAKE = "remote_wake"
ACTION_RESYNC = "resync"
ACTION_NONE = "none"

# Action results
ACTION_RESULT_SUCCESS = "success"
ACTION_RESULT_FAIL = "fail"

# Services
SERVICE_FORCE_ART_ON = "force_art_on"
SERVICE_FORCE_ART_OFF = "force_art_off"
SERVICE_FORCE_TV_ON = "force_tv_on"
SERVICE_FORCE_TV_OFF = "force_tv_off"
SERVICE_RESYNC = "resync"
SERVICE_CLEAR_OVERRIDE = "clear_override"
SERVICE_CLEAR_BREAKER = "clear_breaker"
SERVICE_REPAIR_APPLE_TV = "repair_apple_tv"
SERVICE_REPAIR_SAMSUNG_TV = "repair_samsung_tv"
SERVICE_DELETE_ENTRY = "delete_entry"

# Storage keys
STORAGE_KEY_TOKEN = "frame_token"

